### ISSUE TITLE
Demo site?

### ISSUE THREAD

**Issue by hawkoon** [linnit/2kanna#3]
Is there a demo site available for this software?

**Comment by linnit** [comment]
Yes, [https://2kanna.org/](https://2kanna.org/)

**Comment by GarfieldsPipe** [comment]
> Yes, https://2kanna.org/

Posting is broken;

> Oops! An Error Occurred
> The server returned a "500 Internal Server Error".
> Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by linnit** [comment]
@GarfieldsPipe Just tried a few test posts and didn't have any issues. Anything specific you did to get that error?
